services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/frontend/build/  # build files will be added at this directory

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend:/usr/share/nginx/html/frontend # Copy React App's build files to the Nginx directory

volumes:
  frontend: