name: OWASP Dependency Check

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend Dependency Check
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Use Node.js version 22

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Run OWASP Dependency-Check for Frontend
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'grocery-prices-tracker-web-frontend'
          path: './frontend'
          format: 'HTML'
          out: 'frontend-reports'
          args: '--failOnCVSS 7 --enableRetired'

      # Backend Dependency Check
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'  # Use JDK 21

      - name: Install Backend Dependencies
        run: cd backend && ./gradlew build --no-daemon

      - name: Run OWASP Dependency-Check for Backend
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'grocery-prices-tracker-web-backend'
          path: './backend'
          format: 'HTML'
          out: 'backend-reports'
          args: '--failOnCVSS 7 --enableRetired'

      # Upload Reports
      - name: Upload Frontend Report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dependency-check-report
          path: frontend-reports/dependency-check-report.html
          if-no-files-found: error
          if-exists: replace

      - name: Upload Backend Report
        uses: actions/upload-artifact@v3
        with:
          name: backend-dependency-check-report
          path: backend-reports/dependency-check-report.html
          if-no-files-found: error
          if-exists: replace
